"""Default platform site content (seed for CMS)."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

DEFAULT_BRANDING: dict[str, Any] = {
    "app_name": "Watesly",
    "logo_dark_url": "/brand/watesly-logo-dark.png",
    "logo_light_url": "/brand/watesly-logo-light.png",
    "icon_url": "/brand/watesly-icon.png",
    "hero_image_url": "",
    "primary_color": "#075e54",
    "accent_color": "#25d366",
}

DEFAULT_DISPLAY: dict[str, bool] = {
    "show_hero_mockup": True,
    "show_features": True,
    "show_how": True,
    "show_api": True,
    "show_cta": True,
    "show_stats": True,
    "show_clients": True,
}

LOCALE_DEFAULTS: dict[str, dict[str, Any]] = {
    "ar": {
        "landing": {
            "features": "الميزات",
            "howItWorks": "كيف يعمل",
            "aboutNav": "عن الشركة",
            "clientsNav": "عملاؤنا",
            "api": "واجهة برمجية",
            "signIn": "تسجيل الدخول",
            "getStarted": "ابدأ الآن",
            "pricingNav": "الأسعار",
            "heroEyebrow": "منصة واتساب للمبيعات والدعم",
            "heroTitle": "بيع، خدمة، وتابع عملاءك",
            "heroTitleAccent": " على واتساب — في منصة واحدة.",
            "heroLead": "Watesly (ويتسلي) يجمع صندوق الوارد، الحملات، إدارة علاقات العملاء، دليل المنتجات الذكي، التحليلات، وواجهة برمجية للمطورين — حتى تحوّل كل محادثة إلى فرصة بيع حقيقية.",
            "tryPlatform": "جرّب المنصة",
            "exploreFeatures": "استكشف الميزات",
            "featuresEyebrow": "كل ما تحتاجه",
            "featuresTitle": "منصة متكاملة — وليست مجرد صندوق وارد",
            "featuresSubtitle": "من أول رسالة واردة حتى إغلاق الصفقة والتقرير التنفيذي.",
            "howEyebrow": "بسيط وسريع",
            "howTitle": "كيف يعمل Watesly؟",
            "apiEyebrow": "منصة المطورين",
            "apiTitle": "واجهة برمجية وWebhooks للتوسع",
            "apiBody": "واجهة REST خارجية، مفاتيح محددة النطاق، Webhooks موقّعة، حدود استخدام، وتكاملات سوقية — لربط Watesly مع ERP أو متجرك أو Zapier.",
            "apiDemo": "اطلب عرضًا توضيحيًا للفريق التقني",
            "aboutEyebrow": "من نحن",
            "aboutTitle": "دايركت ديل لتجارة الجملة والتجزئة — مطوّرة Watesly",
            "aboutLead": "نحن شركة كويتية متخصّصة في حلول التجارة والتواصل الرقمي. طورنا Watesly لتمكين الشركات العربية من بيع وخدمة عملائها عبر واتساب باحترافية.",
            "companyLegal": "دايركت ديل لتجارة الجملة والتجزئة",
            "companyProduct": "المنتج: Watesly (ويتسلي)",
            "companyAddress": "الكويت، حولي، قطعة 3، شارع تونس، مجمع الحامد التجاري، ميزانين، مكتب رقم 7",
            "companyPhone": "69950544",
            "companyLocation": "الكويت — حولي",
            "companyEmail": "info@directdealkwt.com",
            "companyWebsite": "www.watesly.com",
            "companyMission": "مهمتنا: تحويل واتساب من قناة محادثات إلى قناة مبيعات ودعم قابلة للقياس والتوسع.",
            "clientsEyebrow": "ثقة وشراكات",
            "clientsTitle": "عملاؤنا وعلاماتنا التجارية",
            "clientsSubtitle": "نفتخر بخدمة شركات وعلامات في قطاعات متعددة — من السياحة والتجميل إلى التجزئة والمواد الغذائية.",
            "ctaTitle": "جاهز لتحويل واتساب إلى قناة مبيعات؟",
            "ctaBody": "ابدأ اليوم — اربط رقمك، أضف منتجاتك، واستقبل أول محادثة.",
            "enterPlatform": "دخول المنصة",
            "footerTagline": "منصة واتساب للمبيعات والدعم والتكامل — من دايركت ديل.",
            "footerCompany": "دايركت ديل لتجارة الجملة والتجزئة",
            "footerAddress": "الكويت، حولي، قطعة 3، شارع تونس، مجمع الحامد التجاري، ميزانين، مكتب 7",
            "footerPhone": "69950544",
            "footerContact": "info@directdealkwt.com",
            "footerRights": "© {{year}} Watesly — دايركت ديل. جميع الحقوق محفوظة.",
        },
        "login": {
            "heroTitle": "بيع وخدمة عملائك على واتساب — بأسعارك الحقيقية.",
            "heroBody": "أضف منتجاتك وخدماتك، والذكاء الاصطناعي يرد على استفسارات العملاء بالأسعار والمواصفات فورًا.",
            "trustCatalog": "✓ دليل منتجات وخدمات",
            "trustAi": "✓ ردود ذكية من أسعارك",
            "trustInbox": "✓ صندوق واتساب موحّد",
        },
        "stats": [
            {"value": "واتساب أولاً", "label": "مصمّمة للسوق العربي"},
            {"value": "ذكاء + مبيعات", "label": "ردود ذكية وصفقات"},
            {"value": "تكامل", "label": "ربط مع أنظمتك"},
            {"value": "حماية البيانات", "label": "امتثال وثقة"},
        ],
        "features": [
            {"icon": "💬", "title": "صندوق وارد واتساب", "desc": "محادثات موحّدة، اتفاقيات مستوى الخدمة، ردود سريعة، ذكاء اصطناعي، وإرسال منتجات من دليل المنتجات مباشرة."},
            {"icon": "👥", "title": "العملاء والحملات", "desc": "إدارة جهات الاتصال، شرائح العملاء، حملات واتساب جماعية، وتقارير التسليم والقراءة."},
            {"icon": "📈", "title": "إدارة علاقات العملاء والصفقات", "desc": "لوحة مبيعات، إنشاء صفقات من المحادثة، مسار المبيعات، وتقارير الإيرادات."},
            {"icon": "🛒", "title": "دليل المنتجات الذكي", "desc": "منتجات وخدمات بأسعارك — الذكاء الاصطناعي يرد على استفسارات الأسعار تلقائيًا."},
            {"icon": "📊", "title": "تحليلات وتقارير", "desc": "لوحة حية، رضا العملاء، أداء الفريق، عائد الحملات، وتصدير Excel."},
            {"icon": "⚡", "title": "واجهة برمجية للمطورين", "desc": "REST API، Webhooks موقّعة، حدود استخدام — للربط مع Zapier وHubSpot."},
        ],
        "steps": [
            {"title": "اربط واتساب", "desc": "اتصل برقم WhatsApp Business API خلال دقائق."},
            {"title": "أضف منتجاتك", "desc": "دليل منتجات، ردود سريعة، وقاعدة معرفة."},
            {"title": "بيع وتابع", "desc": "ردود، حملات، إدارة علاقات العملاء، وتحليلات في مكان واحد."},
        ],
        "mockup": {
            "title": "صندوق وارد Watesly",
            "pill": "٣ محادثات بانتظار الرد",
            "messages": [
                {"role": "incoming", "text": "السلام عليكم، كم سعر الباقة؟"},
                {"role": "outgoing", "text": "أهلاً! الباقة 25 د.ك — تشمل 500 رسالة."},
                {"role": "incoming", "text": "ممتاز، أريد الطلب"},
            ],
            "deal_card": {
                "label": "صفقة مبيعات",
                "title": "باقة واتساب — 25 د.ك",
                "note": "تم إنشاؤها من المحادثة",
            },
        },
        "api": {
            "checklist": [
                "إدارة جهات الاتصال والصفقات",
                "إرسال رسائل عبر الواجهة البرمجية",
                "Webhooks: رسالة واردة، صفقة مكتملة",
                "OpenAPI + Swagger",
            ],
            "code_sample": 'curl -H "Authorization: Bearer mw_..." \\\n  https://api.watesly.com/v1/external/contacts\n\n# Webhook signature\nX-Watesly-Signature: sha256=...',
        },
        "clients": [
            {"icon": "✈️", "name": "ترافل زون", "industry": "السياحة والسفر"},
            {"icon": "✨", "name": "ثري شايني", "industry": "تجارة وتجزئة"},
            {"icon": "💄", "name": "أوليفز", "industry": "مستحضرات التجميل"},
            {"icon": "🛒", "name": "بيغ باغ", "industry": "بقالة ومواد غذائية"},
            {"icon": "🌍", "name": "كينج ترافل", "industry": "السياحة والسفر"},
        ],
    },
    "en": {
        "landing": {
            "features": "Features",
            "howItWorks": "How it works",
            "aboutNav": "About",
            "clientsNav": "Our Clients",
            "api": "API",
            "signIn": "Sign In",
            "getStarted": "Get Started",
            "pricingNav": "Pricing",
            "heroEyebrow": "WhatsApp platform for sales and support",
            "heroTitle": "Sell, support, and follow up",
            "heroTitleAccent": " on WhatsApp — in one platform.",
            "heroLead": "Watesly brings inbox, campaigns, CRM, smart catalog, analytics, and developer API together — so every conversation becomes a real sales opportunity.",
            "tryPlatform": "Try the platform",
            "exploreFeatures": "Explore features",
            "featuresEyebrow": "Everything you need",
            "featuresTitle": "All-in-one platform — not just an inbox",
            "featuresSubtitle": "From the first inbound message to closing the deal and executive reporting.",
            "howEyebrow": "Simple and fast",
            "howTitle": "How does Watesly work?",
            "apiEyebrow": "Developer Platform",
            "apiTitle": "API & Webhooks for scale",
            "apiBody": "External REST API, scoped keys, HMAC-signed webhooks, rate limits, and marketplace integrations — connect Watesly to ERP, your store, or Zapier.",
            "apiDemo": "Request a technical demo",
            "aboutEyebrow": "About us",
            "aboutTitle": "Direct Deal — makers of Watesly",
            "aboutLead": "We are a Kuwait-based company focused on commerce and digital communication. We built Watesly to help Arabic businesses sell and support customers on WhatsApp professionally.",
            "companyLegal": "Direct Deal Wholesale & Retail Trading",
            "companyProduct": "Product: Watesly",
            "companyAddress": "Kuwait, Hawally, Block 3, Tunisia St., Al-Hamed Commercial Complex, Mezzanine, Office 7",
            "companyPhone": "+965 69950544",
            "companyLocation": "Kuwait — Hawally",
            "companyEmail": "info@directdealkwt.com",
            "companyWebsite": "www.watesly.com",
            "companyMission": "Our mission: turn WhatsApp from a chat channel into a measurable, scalable sales and support channel.",
            "clientsEyebrow": "Trust & partnerships",
            "clientsTitle": "Our clients and brands",
            "clientsSubtitle": "We serve companies and brands across tourism, cosmetics, groceries, and retail.",
            "ctaTitle": "Ready to turn WhatsApp into a sales channel?",
            "ctaBody": "Start today — connect your number, add products, and receive your first conversation.",
            "enterPlatform": "Enter platform",
            "footerTagline": "WhatsApp platform for sales, support, and integrations — by Direct Deal.",
            "footerCompany": "Direct Deal Wholesale & Retail Trading",
            "footerAddress": "Kuwait, Hawally, Block 3, Tunisia St., Al-Hamed Commercial Complex, Mezzanine, Office 7",
            "footerPhone": "+965 69950544",
            "footerContact": "info@directdealkwt.com",
            "footerRights": "© {{year}} Watesly — Direct Deal. All rights reserved.",
        },
        "login": {
            "heroTitle": "Sell and support customers on WhatsApp — with your real prices.",
            "heroBody": "Add your products and services, and AI replies to customer questions with prices and specs instantly.",
            "trustCatalog": "✓ Product & service catalog",
            "trustAi": "✓ AI replies from your prices",
            "trustInbox": "✓ Unified WhatsApp inbox",
        },
        "stats": [
            {"value": "WhatsApp-first", "label": "Built for Arabic markets"},
            {"value": "AI + CRM", "label": "Intelligence + sales"},
            {"value": "API", "label": "Integrate with your stack"},
            {"value": "GDPR", "label": "Compliance & trust"},
        ],
        "features": [
            {"icon": "💬", "title": "WhatsApp Inbox", "desc": "Unified conversations, SLA, quick replies, AI, and product sends from your catalog."},
            {"icon": "👥", "title": "Contacts & Campaigns", "desc": "Manage contacts, segments, bulk WhatsApp campaigns, and delivery/read reports."},
            {"icon": "📈", "title": "CRM & Deals", "desc": "Sales Kanban, deals from conversations, pipeline, and revenue reports."},
            {"icon": "🛒", "title": "Smart Catalog", "desc": "Products and services at your prices — AI answers pricing questions automatically."},
            {"icon": "📊", "title": "Analytics & Reports", "desc": "Live dashboard, CSAT, team performance, campaign ROI, and Excel export."},
            {"icon": "⚡", "title": "Developer API", "desc": "REST API, signed webhooks, rate limits — connect with Zapier and HubSpot."},
        ],
        "steps": [
            {"title": "Connect WhatsApp", "desc": "Link your Business API number in minutes."},
            {"title": "Add your products", "desc": "Catalog, quick replies, and knowledge base."},
            {"title": "Sell and follow up", "desc": "Replies, campaigns, CRM, and analytics in one place."},
        ],
        "mockup": {
            "title": "Watesly Inbox",
            "pill": "3 conversations waiting for reply",
            "messages": [
                {"role": "incoming", "text": "Hi, how much is the plan?"},
                {"role": "outgoing", "text": "Hello! The plan is 25 KWD — includes 500 messages."},
                {"role": "incoming", "text": "Great, I want to order"},
            ],
            "deal_card": {
                "label": "CRM Deal",
                "title": "WhatsApp Plan — 25 KWD",
                "note": "Created from conversation",
            },
        },
        "api": {
            "checklist": [
                "GET/POST contacts & CRM deals",
                "Send messages via API",
                "Webhooks: message.received, deal.won",
                "OpenAPI + Swagger",
            ],
            "code_sample": 'curl -H "Authorization: Bearer mw_..." \\\n  https://api.watesly.com/v1/external/contacts\n\n# Webhook signature\nX-Watesly-Signature: sha256=...',
        },
        "clients": [
            {"icon": "✈️", "name": "Travel Zone", "industry": "Tourism & Travel"},
            {"icon": "✨", "name": "Three Shiny", "industry": "Trading & Retail"},
            {"icon": "💄", "name": "Olives", "industry": "Cosmetics"},
            {"icon": "🛒", "name": "Big Bag", "industry": "Groceries & Food"},
            {"icon": "🌍", "name": "King Travel", "industry": "Tourism & Travel"},
        ],
    },
}


def default_site_config() -> dict[str, Any]:
    return {
        "branding": deepcopy(DEFAULT_BRANDING),
        "display": deepcopy(DEFAULT_DISPLAY),
        "locales": deepcopy(LOCALE_DEFAULTS),
    }
