import type { AdminSiteContent } from "../types/siteContent";

export function createDefaultAdminSiteContent(): AdminSiteContent {
  return {
    id: "local-default",
    branding: {
      app_name: "Watesly",
      logo_dark_url: "/brand/watesly-logo-dark.png",
      logo_light_url: "/brand/watesly-logo-light.png",
      icon_url: "/brand/watesly-icon.png",
      hero_image_url: "",
      primary_color: "#075e54",
      accent_color: "#25d366",
    },
    display: {
      show_hero_mockup: true,
      show_features: true,
      show_how: true,
      show_api: true,
      show_cta: true,
      show_stats: true,
    },
    locales: {
      ar: {
        landing: {
          heroEyebrow: "منصة WhatsApp للمبيعات والدعم",
          heroTitle: "بيع، خدمة، وتابع عملاءك",
          heroTitleAccent: " على WhatsApp — في منصة واحدة.",
          heroLead:
            "Watesly يجمع صندوق الوارد، الحملات، CRM، الكتalog الذكي، التحليلات، وAPI للمطورين.",
          tryPlatform: "جرّب المنصة",
          exploreFeatures: "استكشف الميزات",
          featuresEyebrow: "كل ما تحتاجه",
          featuresTitle: "منصة متكاملة — ليس مجرد inbox",
          featuresSubtitle: "من أول رسالة واردة حتى إغلاق الصفقة.",
          howEyebrow: "بسيط وسريع",
          howTitle: "كيف يعمل Watesly؟",
          apiEyebrow: "منصة المطورين",
          apiTitle: "API & Webhooks للتوسع",
          apiBody: "REST API خارجي، webhooks موقّعة، rate limits.",
          apiDemo: "اطلب demo للفريق التقني",
          ctaTitle: "جاهز لتحويل WhatsApp إلى قناة مبيعات؟",
          ctaBody: "ابدأ اليوم — اربط رقمك وأضف منتجاتك.",
          enterPlatform: "دخول المنصة",
          footerTagline: "منصة WhatsApp Business للمبيعات والدعم.",
          footerRights: "© {{year}} Watesly. جميع الحقوق محفوظة.",
        },
        login: {
          heroTitle: "بيع وخدمة عملائك على WhatsApp — بأسعارك الحقيقية.",
          heroBody: "أضف منتجاتك والذكاء الاصطناعي يرد على استفسارات العملاء.",
          trustCatalog: "✓ دليل منتجات وخدمات",
          trustAi: "✓ ردود AI من أسعارك",
          trustInbox: "✓ صندوق واتساب موحّد",
        },
        stats: [
          { value: "WhatsApp-first", label: "مصمم للسوق العربي" },
          { value: "AI + CRM", label: "ذكاء + مبيعات" },
          { value: "API", label: "تكامل مع أنظمتك" },
          { value: "GDPR", label: "امتثال وثقة" },
        ],
        features: [
          { icon: "💬", title: "صندوق وارد WhatsApp", desc: "محادثات موحّدة وردود سريعة." },
          { icon: "👥", title: "العملاء والحملات", desc: "حملات WhatsApp جماعية." },
          { icon: "📈", title: "CRM وصفقات", desc: "Kanban للمبيعات." },
          { icon: "🛒", title: "الكتalog الذكي", desc: "AI يرد على الأسعار." },
          { icon: "📊", title: "تحليلات وتقارير", desc: "لوحة حية وتصدير Excel." },
          { icon: "⚡", title: "API للمطورين", desc: "REST API وwebhooks." },
        ],
        steps: [
          { title: "اربط WhatsApp", desc: "اتصل برقم Business API." },
          { title: "أضف منتجاتك", desc: "كتalog وردود سريعة." },
          { title: "بيع وتابع", desc: "ردود وحملات وCRM." },
        ],
        mockup: {
          title: "Watesly Inbox",
          pill: "3 محادثات بانتظار الرد",
          messages: [
            { role: "incoming", text: "السلام عليكم، كم سعر الباقة؟" },
            { role: "outgoing", text: "أهلاً! الباقة 25 د.ك." },
            { role: "incoming", text: "ممتاز، أريد الطلب" },
          ],
          deal_card: { label: "صفقة CRM", title: "باقة WhatsApp — 25 KWD", note: "من المحادثة" },
        },
        api: {
          checklist: ["GET/POST contacts", "إرسال رسائل عبر API", "Webhooks", "OpenAPI"],
          code_sample: 'curl -H "Authorization: Bearer mw_..." \\\n  https://api.watesly.com/v1/external/contacts',
        },
      },
      en: {
        landing: {
          heroEyebrow: "WhatsApp platform for sales and support",
          heroTitle: "Sell, support, and follow up",
          heroTitleAccent: " on WhatsApp — in one platform.",
          heroLead: "Watesly brings inbox, campaigns, CRM, and analytics together.",
          tryPlatform: "Try the platform",
          exploreFeatures: "Explore features",
          featuresEyebrow: "Everything you need",
          featuresTitle: "All-in-one platform",
          featuresSubtitle: "From first message to closed deal.",
          howEyebrow: "Simple and fast",
          howTitle: "How does Watesly work?",
          apiEyebrow: "Developer Platform",
          apiTitle: "API & Webhooks for scale",
          apiBody: "External REST API, signed webhooks, rate limits.",
          apiDemo: "Request a technical demo",
          ctaTitle: "Ready to turn WhatsApp into a sales channel?",
          ctaBody: "Start today — connect your number.",
          enterPlatform: "Enter platform",
          footerTagline: "WhatsApp Business platform for sales and support.",
          footerRights: "© {{year}} Watesly. All rights reserved.",
        },
        login: {
          heroTitle: "Sell and support customers on WhatsApp.",
          heroBody: "Add products and AI replies instantly.",
          trustCatalog: "✓ Product catalog",
          trustAi: "✓ AI from your prices",
          trustInbox: "✓ Unified inbox",
        },
        stats: [
          { value: "WhatsApp-first", label: "Built for Arabic markets" },
          { value: "AI + CRM", label: "Intelligence + sales" },
          { value: "API", label: "Integrate your stack" },
          { value: "GDPR", label: "Compliance" },
        ],
        features: [
          { icon: "💬", title: "WhatsApp Inbox", desc: "Unified conversations." },
          { icon: "👥", title: "Campaigns", desc: "Bulk WhatsApp campaigns." },
          { icon: "📈", title: "CRM", desc: "Sales Kanban." },
          { icon: "🛒", title: "Smart Catalog", desc: "AI pricing answers." },
          { icon: "📊", title: "Analytics", desc: "Live dashboard." },
          { icon: "⚡", title: "Developer API", desc: "REST and webhooks." },
        ],
        steps: [
          { title: "Connect WhatsApp", desc: "Link Business API." },
          { title: "Add products", desc: "Catalog and quick replies." },
          { title: "Sell and follow up", desc: "Replies, campaigns, CRM." },
        ],
        mockup: {
          title: "Watesly Inbox",
          pill: "3 conversations waiting",
          messages: [
            { role: "incoming", text: "Hi, how much is the plan?" },
            { role: "outgoing", text: "Hello! 25 KWD." },
            { role: "incoming", text: "Great, I want to order" },
          ],
          deal_card: { label: "CRM Deal", title: "WhatsApp Plan — 25 KWD", note: "From conversation" },
        },
        api: {
          checklist: ["GET/POST contacts", "Send messages via API", "Webhooks", "OpenAPI"],
          code_sample: 'curl -H "Authorization: Bearer mw_..." \\\n  https://api.watesly.com/v1/external/contacts',
        },
      },
    },
    is_published: true,
    published_at: null,
    updated_at: new Date().toISOString(),
  };
}
