import type { AdminSiteContent } from "../types/siteContent";

export function createDefaultAdminSiteContent(): AdminSiteContent {
  return {
    id: "local-default",
    branding: {
      app_name: "Watesly",
      logo_dark_url: "/brand/watesly-logo-dark.png",
      logo_light_url: "/brand/watesly-logo-light.png",
      icon_url: "/brand/watesly-icon.png",
      hero_image_url: "",
      primary_color: "#075e54",
      accent_color: "#25d366",
    },
    display: {
      show_hero_mockup: true,
      show_features: true,
      show_how: true,
      show_api: true,
      show_cta: true,
      show_stats: true,
    },
    locales: {
      ar: {
        landing: {
          features: "الميزات",
          howItWorks: "كيف يعمل",
          aboutNav: "عن الشركة",
          api: "واجهة برمجية",
          signIn: "تسجيل الدخول",
          getStarted: "ابدأ الآن",
          pricingNav: "الأسعار",
          heroEyebrow: "منصة واتساب للمبيعات والدعم",
          heroTitle: "بيع، خدمة، وتابع عملاءك",
          heroTitleAccent: " على واتساب — في منصة واحدة.",
          heroLead:
            "Watesly (ويتسلي) يجمع صندوق الوارد، الحملات، إدارة علاقات العملاء، دليل المنتجات الذكي، التحليلات، وواجهة برمجية للمطورين.",
          tryPlatform: "جرّب المنصة",
          exploreFeatures: "استكشف الميزات",
          featuresEyebrow: "كل ما تحتاجه",
          featuresTitle: "منصة متكاملة — وليست مجرد صندوق وارد",
          featuresSubtitle: "من أول رسالة واردة حتى إغلاق الصفقة والتقرير التنفيذي.",
          howEyebrow: "بسيط وسريع",
          howTitle: "كيف يعمل Watesly؟",
          apiEyebrow: "منصة المطورين",
          apiTitle: "واجهة برمجية وWebhooks للتوسع",
          apiBody: "واجهة REST خارجية، Webhooks موقّعة، حدود استخدام، وتكاملات سوقية.",
          apiDemo: "اطلب عرضًا توضيحيًا للفريق التقني",
          aboutEyebrow: "من نحن",
          aboutTitle: "دايركت ديل لتجارة الجملة والتجزئة — مطوّرة Watesly",
          aboutLead:
            "نحن شركة كويتية متخصّصة في حلول التجارة والتواصل الرقمي. طورنا Watesly لتمكين الشركات العربية من بيع وخدمة عملائها عبر واتساب باحترافية.",
          companyLegal: "دايركت ديل لتجارة الجملة والتجزئة",
          companyProduct: "المنتج: Watesly (ويتسلي)",
          companyAddress: "الكويت، حولي، قطعة 3، شارع تونس، مجمع الحامد التجاري، ميزانين، مكتب رقم 7",
          companyPhone: "69950544",
          companyLocation: "الكويت — حولي",
          companyEmail: "info@directdealkwt.com",
          companyWebsite: "www.watesly.com",
          companyMission: "مهمتنا: تحويل واتساب من قناة محادثات إلى قناة مبيعات ودعم قابلة للقياس والتوسع.",
          ctaTitle: "جاهز لتحويل واتساب إلى قناة مبيعات؟",
          ctaBody: "ابدأ اليوم — اربط رقمك وأضف منتجاتك.",
          enterPlatform: "دخول المنصة",
          footerTagline: "منصة واتساب للمبيعات والدعم والتكامل — من دايركت ديل.",
          footerCompany: "دايركت ديل لتجارة الجملة والتجزئة",
          footerAddress: "الكويت، حولي، قطعة 3، شارع تونس، مجمع الحامد التجاري، ميزانين، مكتب 7",
          footerPhone: "69950544",
          footerContact: "info@directdealkwt.com",
          footerRights: "© {{year}} Watesly — دايركت ديل. جميع الحقوق محفوظة.",
        },
        login: {
          heroTitle: "بيع وخدمة عملائك على واتساب — بأسعارك الحقيقية.",
          heroBody: "أضف منتجاتك والذكاء الاصطناعي يرد على استفسارات العملاء.",
          trustCatalog: "✓ دليل منتجات وخدمات",
          trustAi: "✓ ردود ذكية من أسعارك",
          trustInbox: "✓ صندوق واتساب موحّد",
        },
        stats: [
          { value: "واتساب أولاً", label: "مصمّمة للسوق العربي" },
          { value: "ذكاء + مبيعات", label: "ردود ذكية وصفقات" },
          { value: "تكامل", label: "ربط مع أنظمتك" },
          { value: "حماية البيانات", label: "امتثال وثقة" },
        ],
        features: [
          { icon: "💬", title: "صندوق وارد واتساب", desc: "محادثات موحّدة، ردود سريعة، وذكاء اصطناعي." },
          { icon: "👥", title: "العملاء والحملات", desc: "شرائح العملاء وحملات واتساب جماعية." },
          { icon: "📈", title: "إدارة علاقات العملاء", desc: "لوحة مبيعات وصفقات من المحادثة." },
          { icon: "🛒", title: "دليل المنتجات الذكي", desc: "الذكاء الاصطناعي يرد على الأسعار." },
          { icon: "📊", title: "تحليلات وتقارير", desc: "لوحة حية وتصدير Excel." },
          { icon: "⚡", title: "واجهة برمجية", desc: "REST API وWebhooks." },
        ],
        steps: [
          { title: "اربط واتساب", desc: "اتصل برقم WhatsApp Business API." },
          { title: "أضف منتجاتك", desc: "دليل منتجات وردود سريعة." },
          { title: "بيع وتابع", desc: "ردود، حملات، وتحليلات." },
        ],
        mockup: {
          title: "صندوق وارد Watesly",
          pill: "٣ محادثات بانتظار الرد",
          messages: [
            { role: "incoming", text: "السلام عليكم، كم سعر الباقة؟" },
            { role: "outgoing", text: "أهلاً! الباقة 25 د.ك." },
            { role: "incoming", text: "ممتاز، أريد الطلب" },
          ],
          deal_card: { label: "صفقة مبيعات", title: "باقة واتساب — 25 د.ك", note: "من المحادثة" },
        },
        api: {
          checklist: ["إدارة جهات الاتصال", "إرسال رسائل عبر API", "Webhooks", "OpenAPI"],
          code_sample: 'curl -H "Authorization: Bearer mw_..." \\\n  https://api.watesly.com/v1/external/contacts',
        },
      },
      en: {
        landing: {
          features: "Features",
          howItWorks: "How it works",
          aboutNav: "About",
          api: "API",
          signIn: "Sign In",
          getStarted: "Get Started",
          pricingNav: "Pricing",
          heroEyebrow: "WhatsApp platform for sales and support",
          heroTitle: "Sell, support, and follow up",
          heroTitleAccent: " on WhatsApp — in one platform.",
          heroLead: "Watesly brings inbox, campaigns, CRM, and analytics together.",
          tryPlatform: "Try the platform",
          exploreFeatures: "Explore features",
          featuresEyebrow: "Everything you need",
          featuresTitle: "All-in-one platform",
          featuresSubtitle: "From first message to closed deal.",
          howEyebrow: "Simple and fast",
          howTitle: "How does Watesly work?",
          apiEyebrow: "Developer Platform",
          apiTitle: "API & Webhooks for scale",
          apiBody: "External REST API, signed webhooks, rate limits.",
          apiDemo: "Request a technical demo",
          aboutEyebrow: "About us",
          aboutTitle: "Direct Deal — makers of Watesly",
          aboutLead: "Kuwait-based commerce and digital communication solutions.",
          companyLegal: "Direct Deal Wholesale & Retail Trading",
          companyProduct: "Product: Watesly",
          companyAddress: "Kuwait, Hawally, Block 3, Tunisia St., Al-Hamed Commercial Complex, Mezzanine, Office 7",
          companyPhone: "+965 69950544",
          companyLocation: "Kuwait — Hawally",
          companyEmail: "info@directdealkwt.com",
          companyWebsite: "www.watesly.com",
          companyMission: "Turn WhatsApp into a measurable sales and support channel.",
          ctaTitle: "Ready to turn WhatsApp into a sales channel?",
          ctaBody: "Start today — connect your number.",
          enterPlatform: "Enter platform",
          footerTagline: "WhatsApp platform by Direct Deal.",
          footerCompany: "Direct Deal Wholesale & Retail Trading",
          footerAddress: "Kuwait, Hawally, Block 3, Tunisia St., Al-Hamed Commercial Complex, Mezzanine, Office 7",
          footerPhone: "+965 69950544",
          footerContact: "info@directdealkwt.com",
          footerRights: "© {{year}} Watesly — Direct Deal. All rights reserved.",
        },
        login: {
          heroTitle: "Sell and support customers on WhatsApp.",
          heroBody: "Add products and AI replies instantly.",
          trustCatalog: "✓ Product catalog",
          trustAi: "✓ AI from your prices",
          trustInbox: "✓ Unified inbox",
        },
        stats: [
          { value: "WhatsApp-first", label: "Built for Arabic markets" },
          { value: "AI + CRM", label: "Intelligence + sales" },
          { value: "API", label: "Integrate your stack" },
          { value: "GDPR", label: "Compliance" },
        ],
        features: [
          { icon: "💬", title: "WhatsApp Inbox", desc: "Unified conversations." },
          { icon: "👥", title: "Campaigns", desc: "Bulk WhatsApp campaigns." },
          { icon: "📈", title: "CRM", desc: "Sales Kanban." },
          { icon: "🛒", title: "Smart Catalog", desc: "AI pricing answers." },
          { icon: "📊", title: "Analytics", desc: "Live dashboard." },
          { icon: "⚡", title: "Developer API", desc: "REST and webhooks." },
        ],
        steps: [
          { title: "Connect WhatsApp", desc: "Link Business API." },
          { title: "Add products", desc: "Catalog and quick replies." },
          { title: "Sell and follow up", desc: "Replies, campaigns, CRM." },
        ],
        mockup: {
          title: "Watesly Inbox",
          pill: "3 conversations waiting",
          messages: [
            { role: "incoming", text: "Hi, how much is the plan?" },
            { role: "outgoing", text: "Hello! 25 KWD." },
            { role: "incoming", text: "Great, I want to order" },
          ],
          deal_card: { label: "CRM Deal", title: "WhatsApp Plan — 25 KWD", note: "From conversation" },
        },
        api: {
          checklist: ["GET/POST contacts", "Send messages via API", "Webhooks", "OpenAPI"],
          code_sample: 'curl -H "Authorization: Bearer mw_..." \\\n  https://api.watesly.com/v1/external/contacts',
        },
      },
    },
    is_published: true,
    published_at: null,
    updated_at: new Date().toISOString(),
  };
}
